"""initial schema

Revision ID: aa3f67362dd4
Revises: 
Create Date: 2026-09-17 21:42:47.245652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3f67362dd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('orthodontist')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_cities_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('owner_id', 'name_key', name=op.f('uq_cities_owner_id_name_key'))
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_owner_id'), ['owner_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_doctors_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('owner_id', 'name_key', name=op.f('uq_doctors_owner_id_name_key'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_owner_id'), ['owner_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_key', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_patients_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_owner_id'), ['owner_id'], unique=False)

    op.create_table('treatment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_treatment_types_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_types')),
    sa.UniqueConstraint('owner_id', 'name_key', name=op.f('uq_treatment_types_owner_id_name_key'))
    )
    with op.batch_alter_table('treatment_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_types_owner_id'), ['owner_id'], unique=False)

    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('branch_key', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_clinics_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_clinics_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics')),
    sa.UniqueConstraint('owner_id', 'city_id', 'name_key', 'branch_key', name=op.f('uq_clinics_owner_id_city_id_name_key_branch_key'))
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinics_owner_id'), ['owner_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('quote_amount', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('consultation', 'active', 'completed', 'discontinued')", name=op.f('ck_cases_status')),
    sa.CheckConstraint('quote_amount >= 0 AND fee_amount >= 0 AND material_cost >= 0', name=op.f('ck_cases_non_negative')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_cases_clinic_id_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_cases_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_cases_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_cases_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_type_id'], ['treatment_types.id'], name=op.f('fk_cases_treatment_type_id_treatment_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_started_on'), ['started_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_treatment_type_id'), ['treatment_type_id'], unique=False)

    op.create_table('clinic_doctors',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_doctors_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_clinic_doctors_doctor_id_doctors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clinic_id', 'doctor_id', name=op.f('pk_clinic_doctors'))
    )
    op.create_table('rate_card_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type_id', sa.Integer(), nullable=False),
    sa.Column('quote_amount', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quote_amount >= 0 AND fee_amount >= 0 AND material_cost >= 0', name=op.f('ck_rate_card_entries_non_negative')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_rate_card_entries_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_type_id'], ['treatment_types.id'], name=op.f('fk_rate_card_entries_treatment_type_id_treatment_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_card_entries')),
    sa.UniqueConstraint('clinic_id', 'treatment_type_id', name=op.f('uq_rate_card_entries_clinic_id_treatment_type_id'))
    )
    with op.batch_alter_table('rate_card_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_card_entries_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_card_entries_treatment_type_id'), ['treatment_type_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'no_show')", name=op.f('ck_appointments_status')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_appointments_duration_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_appointments_case_id_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_appointments_clinic_id_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_appointments_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_starts_at'), ['starts_at'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('stage_label', sa.String(length=120), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_photos_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_photos_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_owner_id'), ['owner_id'], unique=False)

    op.create_table('photo_files',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('full_jpeg', sa.LargeBinary(), nullable=False),
    sa.Column('thumb_jpeg', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_files_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', name=op.f('pk_photo_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_files')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_owner_id'))
        batch_op.drop_index(batch_op.f('ix_photos_case_id'))

    op.drop_table('photos')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_case_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('rate_card_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_card_entries_treatment_type_id'))
        batch_op.drop_index(batch_op.f('ix_rate_card_entries_clinic_id'))

    op.drop_table('rate_card_entries')
    op.drop_table('clinic_doctors')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_treatment_type_id'))
        batch_op.drop_index(batch_op.f('ix_cases_started_on'))
        batch_op.drop_index(batch_op.f('ix_cases_patient_id'))
        batch_op.drop_index(batch_op.f('ix_cases_owner_id'))
        batch_op.drop_index(batch_op.f('ix_cases_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_cases_clinic_id'))

    op.drop_table('cases')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_owner_id'))
        batch_op.drop_index(batch_op.f('ix_clinics_city_id'))

    op.drop_table('clinics')
    with op.batch_alter_table('treatment_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_types_owner_id'))

    op.drop_table('treatment_types')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_owner_id'))
        batch_op.drop_index(batch_op.f('ix_patients_name_key'))

    op.drop_table('patients')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_owner_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_owner_id'))

    op.drop_table('cities')
    op.drop_table('users')
    # ### end Alembic commands ###
